// Code generated by generator/main.go; DO NOT EDIT.

package entity

type (
	AcaciaBoat           struct{}
	AcaciaChestBoat      struct{}
	Allay                struct{}
	AreaEffectCloud      struct{}
	Armadillo            struct{}
	ArmorStand           struct{}
	Arrow                struct{}
	Axolotl              struct{}
	BambooChestRaft      struct{}
	BambooRaft           struct{}
	Bat                  struct{}
	Bee                  struct{}
	BirchBoat            struct{}
	BirchChestBoat       struct{}
	Blaze                struct{}
	BlockDisplay         struct{}
	Bogged               struct{}
	Breeze               struct{}
	BreezeWindCharge     struct{}
	Camel                struct{}
	CamelHusk            struct{}
	Cat                  struct{}
	CaveSpider           struct{}
	CherryBoat           struct{}
	CherryChestBoat      struct{}
	ChestMinecart        struct{}
	Chicken              struct{}
	Cod                  struct{}
	CopperGolem          struct{}
	CommandBlockMinecart struct{}
	Cow                  struct{}
	Creaking             struct{}
	Creeper              struct{}
	DarkOakBoat          struct{}
	DarkOakChestBoat     struct{}
	Dolphin              struct{}
	Donkey               struct{}
	DragonFireball       struct{}
	Drowned              struct{}
	Egg                  struct{}
	ElderGuardian        struct{}
	Enderman             struct{}
	Endermite            struct{}
	EnderDragon          struct{}
	EnderPearl           struct{}
	EndCrystal           struct{}
	Evoker               struct{}
	EvokerFangs          struct{}
	ExperienceBottle     struct{}
	ExperienceOrb        struct{}
	EyeOfEnder           struct{}
	FallingBlock         struct{}
	Fireball             struct{}
	FireworkRocket       struct{}
	Fox                  struct{}
	Frog                 struct{}
	FurnaceMinecart      struct{}
	Ghast                struct{}
	HappyGhast           struct{}
	Giant                struct{}
	GlowItemFrame        struct{}
	GlowSquid            struct{}
	Goat                 struct{}
	Guardian             struct{}
	Hoglin               struct{}
	HopperMinecart       struct{}
	Horse                struct{}
	Husk                 struct{}
	Illusioner           struct{}
	Interaction          struct{}
	IronGolem            struct{}
	Item                 struct{}
	ItemDisplay          struct{}
	ItemFrame            struct{}
	JungleBoat           struct{}
	JungleChestBoat      struct{}
	LeashKnot            struct{}
	LightningBolt        struct{}
	Llama                struct{}
	LlamaSpit            struct{}
	MagmaCube            struct{}
	MangroveBoat         struct{}
	MangroveChestBoat    struct{}
	Mannequin            struct{}
	Marker               struct{}
	Minecart             struct{}
	Mooshroom            struct{}
	Mule                 struct{}
	Nautilus             struct{}
	OakBoat              struct{}
	OakChestBoat         struct{}
	Ocelot               struct{}
	OminousItemSpawner   struct{}
	Painting             struct{}
	PaleOakBoat          struct{}
	PaleOakChestBoat     struct{}
	Panda                struct{}
	Parched              struct{}
	Parrot               struct{}
	Phantom              struct{}
	Pig                  struct{}
	Piglin               struct{}
	PiglinBrute          struct{}
	Pillager             struct{}
	PolarBear            struct{}
	SplashPotion         struct{}
	LingeringPotion      struct{}
	Pufferfish           struct{}
	Rabbit               struct{}
	Ravager              struct{}
	Salmon               struct{}
	Sheep                struct{}
	Shulker              struct{}
	ShulkerBullet        struct{}
	Silverfish           struct{}
	Skeleton             struct{}
	SkeletonHorse        struct{}
	Slime                struct{}
	SmallFireball        struct{}
	Sniffer              struct{}
	Snowball             struct{}
	SnowGolem            struct{}
	SpawnerMinecart      struct{}
	SpectralArrow        struct{}
	Spider               struct{}
	SpruceBoat           struct{}
	SpruceChestBoat      struct{}
	Squid                struct{}
	Stray                struct{}
	Strider              struct{}
	Tadpole              struct{}
	TextDisplay          struct{}
	Tnt                  struct{}
	TntMinecart          struct{}
	TraderLlama          struct{}
	Trident              struct{}
	TropicalFish         struct{}
	Turtle               struct{}
	Vex                  struct{}
	Villager             struct{}
	Vindicator           struct{}
	WanderingTrader      struct{}
	Warden               struct{}
	WindCharge           struct{}
	Witch                struct{}
	Wither               struct{}
	WitherSkeleton       struct{}
	WitherSkull          struct{}
	Wolf                 struct{}
	Zoglin               struct{}
	Zombie               struct{}
	ZombieHorse          struct{}
	ZombieNautilus       struct{}
	ZombieVillager       struct{}
	ZombifiedPiglin      struct{}
	Player               struct{}
	FishingBobber        struct{}
)

func (AcaciaBoat) ID() string                { return "minecraft:acacia_boat" }
func (AcaciaBoat) Width() float32            { return 1.375000 }
func (AcaciaBoat) Height() float32           { return 0.562500 }
func (AcaciaChestBoat) ID() string           { return "minecraft:acacia_chest_boat" }
func (AcaciaChestBoat) Width() float32       { return 1.375000 }
func (AcaciaChestBoat) Height() float32      { return 0.562500 }
func (Allay) ID() string                     { return "minecraft:allay" }
func (Allay) Width() float32                 { return 0.350000 }
func (Allay) Height() float32                { return 0.600000 }
func (AreaEffectCloud) ID() string           { return "minecraft:area_effect_cloud" }
func (AreaEffectCloud) Width() float32       { return 6.000000 }
func (AreaEffectCloud) Height() float32      { return 0.500000 }
func (Armadillo) ID() string                 { return "minecraft:armadillo" }
func (Armadillo) Width() float32             { return 0.700000 }
func (Armadillo) Height() float32            { return 0.650000 }
func (ArmorStand) ID() string                { return "minecraft:armor_stand" }
func (ArmorStand) Width() float32            { return 0.500000 }
func (ArmorStand) Height() float32           { return 1.975000 }
func (Arrow) ID() string                     { return "minecraft:arrow" }
func (Arrow) Width() float32                 { return 0.500000 }
func (Arrow) Height() float32                { return 0.500000 }
func (Axolotl) ID() string                   { return "minecraft:axolotl" }
func (Axolotl) Width() float32               { return 0.750000 }
func (Axolotl) Height() float32              { return 0.420000 }
func (BambooChestRaft) ID() string           { return "minecraft:bamboo_chest_raft" }
func (BambooChestRaft) Width() float32       { return 1.375000 }
func (BambooChestRaft) Height() float32      { return 0.562500 }
func (BambooRaft) ID() string                { return "minecraft:bamboo_raft" }
func (BambooRaft) Width() float32            { return 1.375000 }
func (BambooRaft) Height() float32           { return 0.562500 }
func (Bat) ID() string                       { return "minecraft:bat" }
func (Bat) Width() float32                   { return 0.500000 }
func (Bat) Height() float32                  { return 0.900000 }
func (Bee) ID() string                       { return "minecraft:bee" }
func (Bee) Width() float32                   { return 0.700000 }
func (Bee) Height() float32                  { return 0.600000 }
func (BirchBoat) ID() string                 { return "minecraft:birch_boat" }
func (BirchBoat) Width() float32             { return 1.375000 }
func (BirchBoat) Height() float32            { return 0.562500 }
func (BirchChestBoat) ID() string            { return "minecraft:birch_chest_boat" }
func (BirchChestBoat) Width() float32        { return 1.375000 }
func (BirchChestBoat) Height() float32       { return 0.562500 }
func (Blaze) ID() string                     { return "minecraft:blaze" }
func (Blaze) Width() float32                 { return 0.600000 }
func (Blaze) Height() float32                { return 1.800000 }
func (BlockDisplay) ID() string              { return "minecraft:block_display" }
func (BlockDisplay) Width() float32          { return 0.000000 }
func (BlockDisplay) Height() float32         { return 0.000000 }
func (Bogged) ID() string                    { return "minecraft:bogged" }
func (Bogged) Width() float32                { return 0.600000 }
func (Bogged) Height() float32               { return 1.990000 }
func (Breeze) ID() string                    { return "minecraft:breeze" }
func (Breeze) Width() float32                { return 0.600000 }
func (Breeze) Height() float32               { return 1.770000 }
func (BreezeWindCharge) ID() string          { return "minecraft:breeze_wind_charge" }
func (BreezeWindCharge) Width() float32      { return 0.312500 }
func (BreezeWindCharge) Height() float32     { return 0.312500 }
func (Camel) ID() string                     { return "minecraft:camel" }
func (Camel) Width() float32                 { return 1.700000 }
func (Camel) Height() float32                { return 2.375000 }
func (CamelHusk) ID() string                 { return "minecraft:camel_husk" }
func (CamelHusk) Width() float32             { return 1.700000 }
func (CamelHusk) Height() float32            { return 2.375000 }
func (Cat) ID() string                       { return "minecraft:cat" }
func (Cat) Width() float32                   { return 0.600000 }
func (Cat) Height() float32                  { return 0.700000 }
func (CaveSpider) ID() string                { return "minecraft:cave_spider" }
func (CaveSpider) Width() float32            { return 0.700000 }
func (CaveSpider) Height() float32           { return 0.500000 }
func (CherryBoat) ID() string                { return "minecraft:cherry_boat" }
func (CherryBoat) Width() float32            { return 1.375000 }
func (CherryBoat) Height() float32           { return 0.562500 }
func (CherryChestBoat) ID() string           { return "minecraft:cherry_chest_boat" }
func (CherryChestBoat) Width() float32       { return 1.375000 }
func (CherryChestBoat) Height() float32      { return 0.562500 }
func (ChestMinecart) ID() string             { return "minecraft:chest_minecart" }
func (ChestMinecart) Width() float32         { return 0.980000 }
func (ChestMinecart) Height() float32        { return 0.700000 }
func (Chicken) ID() string                   { return "minecraft:chicken" }
func (Chicken) Width() float32               { return 0.400000 }
func (Chicken) Height() float32              { return 0.700000 }
func (Cod) ID() string                       { return "minecraft:cod" }
func (Cod) Width() float32                   { return 0.500000 }
func (Cod) Height() float32                  { return 0.300000 }
func (CopperGolem) ID() string               { return "minecraft:copper_golem" }
func (CopperGolem) Width() float32           { return 0.490000 }
func (CopperGolem) Height() float32          { return 0.980000 }
func (CommandBlockMinecart) ID() string      { return "minecraft:command_block_minecart" }
func (CommandBlockMinecart) Width() float32  { return 0.980000 }
func (CommandBlockMinecart) Height() float32 { return 0.700000 }
func (Cow) ID() string                       { return "minecraft:cow" }
func (Cow) Width() float32                   { return 0.900000 }
func (Cow) Height() float32                  { return 1.400000 }
func (Creaking) ID() string                  { return "minecraft:creaking" }
func (Creaking) Width() float32              { return 0.900000 }
func (Creaking) Height() float32             { return 2.700000 }
func (Creeper) ID() string                   { return "minecraft:creeper" }
func (Creeper) Width() float32               { return 0.600000 }
func (Creeper) Height() float32              { return 1.700000 }
func (DarkOakBoat) ID() string               { return "minecraft:dark_oak_boat" }
func (DarkOakBoat) Width() float32           { return 1.375000 }
func (DarkOakBoat) Height() float32          { return 0.562500 }
func (DarkOakChestBoat) ID() string          { return "minecraft:dark_oak_chest_boat" }
func (DarkOakChestBoat) Width() float32      { return 1.375000 }
func (DarkOakChestBoat) Height() float32     { return 0.562500 }
func (Dolphin) ID() string                   { return "minecraft:dolphin" }
func (Dolphin) Width() float32               { return 0.900000 }
func (Dolphin) Height() float32              { return 0.600000 }
func (Donkey) ID() string                    { return "minecraft:donkey" }
func (Donkey) Width() float32                { return 1.396484 }
func (Donkey) Height() float32               { return 1.500000 }
func (DragonFireball) ID() string            { return "minecraft:dragon_fireball" }
func (DragonFireball) Width() float32        { return 1.000000 }
func (DragonFireball) Height() float32       { return 1.000000 }
func (Drowned) ID() string                   { return "minecraft:drowned" }
func (Drowned) Width() float32               { return 0.600000 }
func (Drowned) Height() float32              { return 1.950000 }
func (Egg) ID() string                       { return "minecraft:egg" }
func (Egg) Width() float32                   { return 0.250000 }
func (Egg) Height() float32                  { return 0.250000 }
func (ElderGuardian) ID() string             { return "minecraft:elder_guardian" }
func (ElderGuardian) Width() float32         { return 1.997500 }
func (ElderGuardian) Height() float32        { return 1.997500 }
func (Enderman) ID() string                  { return "minecraft:enderman" }
func (Enderman) Width() float32              { return 0.600000 }
func (Enderman) Height() float32             { return 2.900000 }
func (Endermite) ID() string                 { return "minecraft:endermite" }
func (Endermite) Width() float32             { return 0.400000 }
func (Endermite) Height() float32            { return 0.300000 }
func (EnderDragon) ID() string               { return "minecraft:ender_dragon" }
func (EnderDragon) Width() float32           { return 16.000000 }
func (EnderDragon) Height() float32          { return 8.000000 }
func (EnderPearl) ID() string                { return "minecraft:ender_pearl" }
func (EnderPearl) Width() float32            { return 0.250000 }
func (EnderPearl) Height() float32           { return 0.250000 }
func (EndCrystal) ID() string                { return "minecraft:end_crystal" }
func (EndCrystal) Width() float32            { return 2.000000 }
func (EndCrystal) Height() float32           { return 2.000000 }
func (Evoker) ID() string                    { return "minecraft:evoker" }
func (Evoker) Width() float32                { return 0.600000 }
func (Evoker) Height() float32               { return 1.950000 }
func (EvokerFangs) ID() string               { return "minecraft:evoker_fangs" }
func (EvokerFangs) Width() float32           { return 0.500000 }
func (EvokerFangs) Height() float32          { return 0.800000 }
func (ExperienceBottle) ID() string          { return "minecraft:experience_bottle" }
func (ExperienceBottle) Width() float32      { return 0.250000 }
func (ExperienceBottle) Height() float32     { return 0.250000 }
func (ExperienceOrb) ID() string             { return "minecraft:experience_orb" }
func (ExperienceOrb) Width() float32         { return 0.500000 }
func (ExperienceOrb) Height() float32        { return 0.500000 }
func (EyeOfEnder) ID() string                { return "minecraft:eye_of_ender" }
func (EyeOfEnder) Width() float32            { return 0.250000 }
func (EyeOfEnder) Height() float32           { return 0.250000 }
func (FallingBlock) ID() string              { return "minecraft:falling_block" }
func (FallingBlock) Width() float32          { return 0.980000 }
func (FallingBlock) Height() float32         { return 0.980000 }
func (Fireball) ID() string                  { return "minecraft:fireball" }
func (Fireball) Width() float32              { return 1.000000 }
func (Fireball) Height() float32             { return 1.000000 }
func (FireworkRocket) ID() string            { return "minecraft:firework_rocket" }
func (FireworkRocket) Width() float32        { return 0.250000 }
func (FireworkRocket) Height() float32       { return 0.250000 }
func (Fox) ID() string                       { return "minecraft:fox" }
func (Fox) Width() float32                   { return 0.600000 }
func (Fox) Height() float32                  { return 0.700000 }
func (Frog) ID() string                      { return "minecraft:frog" }
func (Frog) Width() float32                  { return 0.500000 }
func (Frog) Height() float32                 { return 0.500000 }
func (FurnaceMinecart) ID() string           { return "minecraft:furnace_minecart" }
func (FurnaceMinecart) Width() float32       { return 0.980000 }
func (FurnaceMinecart) Height() float32      { return 0.700000 }
func (Ghast) ID() string                     { return "minecraft:ghast" }
func (Ghast) Width() float32                 { return 4.000000 }
func (Ghast) Height() float32                { return 4.000000 }
func (HappyGhast) ID() string                { return "minecraft:happy_ghast" }
func (HappyGhast) Width() float32            { return 4.000000 }
func (HappyGhast) Height() float32           { return 4.000000 }
func (Giant) ID() string                     { return "minecraft:giant" }
func (Giant) Width() float32                 { return 3.600000 }
func (Giant) Height() float32                { return 12.000000 }
func (GlowItemFrame) ID() string             { return "minecraft:glow_item_frame" }
func (GlowItemFrame) Width() float32         { return 0.500000 }
func (GlowItemFrame) Height() float32        { return 0.500000 }
func (GlowSquid) ID() string                 { return "minecraft:glow_squid" }
func (GlowSquid) Width() float32             { return 0.800000 }
func (GlowSquid) Height() float32            { return 0.800000 }
func (Goat) ID() string                      { return "minecraft:goat" }
func (Goat) Width() float32                  { return 0.900000 }
func (Goat) Height() float32                 { return 1.300000 }
func (Guardian) ID() string                  { return "minecraft:guardian" }
func (Guardian) Width() float32              { return 0.850000 }
func (Guardian) Height() float32             { return 0.850000 }
func (Hoglin) ID() string                    { return "minecraft:hoglin" }
func (Hoglin) Width() float32                { return 1.396484 }
func (Hoglin) Height() float32               { return 1.400000 }
func (HopperMinecart) ID() string            { return "minecraft:hopper_minecart" }
func (HopperMinecart) Width() float32        { return 0.980000 }
func (HopperMinecart) Height() float32       { return 0.700000 }
func (Horse) ID() string                     { return "minecraft:horse" }
func (Horse) Width() float32                 { return 1.396484 }
func (Horse) Height() float32                { return 1.600000 }
func (Husk) ID() string                      { return "minecraft:husk" }
func (Husk) Width() float32                  { return 0.600000 }
func (Husk) Height() float32                 { return 1.950000 }
func (Illusioner) ID() string                { return "minecraft:illusioner" }
func (Illusioner) Width() float32            { return 0.600000 }
func (Illusioner) Height() float32           { return 1.950000 }
func (Interaction) ID() string               { return "minecraft:interaction" }
func (Interaction) Width() float32           { return 0.000000 }
func (Interaction) Height() float32          { return 0.000000 }
func (IronGolem) ID() string                 { return "minecraft:iron_golem" }
func (IronGolem) Width() float32             { return 1.400000 }
func (IronGolem) Height() float32            { return 2.700000 }
func (Item) ID() string                      { return "minecraft:item" }
func (Item) Width() float32                  { return 0.250000 }
func (Item) Height() float32                 { return 0.250000 }
func (ItemDisplay) ID() string               { return "minecraft:item_display" }
func (ItemDisplay) Width() float32           { return 0.000000 }
func (ItemDisplay) Height() float32          { return 0.000000 }
func (ItemFrame) ID() string                 { return "minecraft:item_frame" }
func (ItemFrame) Width() float32             { return 0.500000 }
func (ItemFrame) Height() float32            { return 0.500000 }
func (JungleBoat) ID() string                { return "minecraft:jungle_boat" }
func (JungleBoat) Width() float32            { return 1.375000 }
func (JungleBoat) Height() float32           { return 0.562500 }
func (JungleChestBoat) ID() string           { return "minecraft:jungle_chest_boat" }
func (JungleChestBoat) Width() float32       { return 1.375000 }
func (JungleChestBoat) Height() float32      { return 0.562500 }
func (LeashKnot) ID() string                 { return "minecraft:leash_knot" }
func (LeashKnot) Width() float32             { return 0.375000 }
func (LeashKnot) Height() float32            { return 0.500000 }
func (LightningBolt) ID() string             { return "minecraft:lightning_bolt" }
func (LightningBolt) Width() float32         { return 0.000000 }
func (LightningBolt) Height() float32        { return 0.000000 }
func (Llama) ID() string                     { return "minecraft:llama" }
func (Llama) Width() float32                 { return 0.900000 }
func (Llama) Height() float32                { return 1.870000 }
func (LlamaSpit) ID() string                 { return "minecraft:llama_spit" }
func (LlamaSpit) Width() float32             { return 0.250000 }
func (LlamaSpit) Height() float32            { return 0.250000 }
func (MagmaCube) ID() string                 { return "minecraft:magma_cube" }
func (MagmaCube) Width() float32             { return 0.520000 }
func (MagmaCube) Height() float32            { return 0.520000 }
func (MangroveBoat) ID() string              { return "minecraft:mangrove_boat" }
func (MangroveBoat) Width() float32          { return 1.375000 }
func (MangroveBoat) Height() float32         { return 0.562500 }
func (MangroveChestBoat) ID() string         { return "minecraft:mangrove_chest_boat" }
func (MangroveChestBoat) Width() float32     { return 1.375000 }
func (MangroveChestBoat) Height() float32    { return 0.562500 }
func (Mannequin) ID() string                 { return "minecraft:mannequin" }
func (Mannequin) Width() float32             { return 0.600000 }
func (Mannequin) Height() float32            { return 1.800000 }
func (Marker) ID() string                    { return "minecraft:marker" }
func (Marker) Width() float32                { return 0.000000 }
func (Marker) Height() float32               { return 0.000000 }
func (Minecart) ID() string                  { return "minecraft:minecart" }
func (Minecart) Width() float32              { return 0.980000 }
func (Minecart) Height() float32             { return 0.700000 }
func (Mooshroom) ID() string                 { return "minecraft:mooshroom" }
func (Mooshroom) Width() float32             { return 0.900000 }
func (Mooshroom) Height() float32            { return 1.400000 }
func (Mule) ID() string                      { return "minecraft:mule" }
func (Mule) Width() float32                  { return 1.396484 }
func (Mule) Height() float32                 { return 1.600000 }
func (Nautilus) ID() string                  { return "minecraft:nautilus" }
func (Nautilus) Width() float32              { return 0.875000 }
func (Nautilus) Height() float32             { return 0.950000 }
func (OakBoat) ID() string                   { return "minecraft:oak_boat" }
func (OakBoat) Width() float32               { return 1.375000 }
func (OakBoat) Height() float32              { return 0.562500 }
func (OakChestBoat) ID() string              { return "minecraft:oak_chest_boat" }
func (OakChestBoat) Width() float32          { return 1.375000 }
func (OakChestBoat) Height() float32         { return 0.562500 }
func (Ocelot) ID() string                    { return "minecraft:ocelot" }
func (Ocelot) Width() float32                { return 0.600000 }
func (Ocelot) Height() float32               { return 0.700000 }
func (OminousItemSpawner) ID() string        { return "minecraft:ominous_item_spawner" }
func (OminousItemSpawner) Width() float32    { return 0.250000 }
func (OminousItemSpawner) Height() float32   { return 0.250000 }
func (Painting) ID() string                  { return "minecraft:painting" }
func (Painting) Width() float32              { return 0.500000 }
func (Painting) Height() float32             { return 0.500000 }
func (PaleOakBoat) ID() string               { return "minecraft:pale_oak_boat" }
func (PaleOakBoat) Width() float32           { return 1.375000 }
func (PaleOakBoat) Height() float32          { return 0.562500 }
func (PaleOakChestBoat) ID() string          { return "minecraft:pale_oak_chest_boat" }
func (PaleOakChestBoat) Width() float32      { return 1.375000 }
func (PaleOakChestBoat) Height() float32     { return 0.562500 }
func (Panda) ID() string                     { return "minecraft:panda" }
func (Panda) Width() float32                 { return 1.300000 }
func (Panda) Height() float32                { return 1.250000 }
func (Parched) ID() string                   { return "minecraft:parched" }
func (Parched) Width() float32               { return 0.600000 }
func (Parched) Height() float32              { return 1.990000 }
func (Parrot) ID() string                    { return "minecraft:parrot" }
func (Parrot) Width() float32                { return 0.500000 }
func (Parrot) Height() float32               { return 0.900000 }
func (Phantom) ID() string                   { return "minecraft:phantom" }
func (Phantom) Width() float32               { return 0.900000 }
func (Phantom) Height() float32              { return 0.500000 }
func (Pig) ID() string                       { return "minecraft:pig" }
func (Pig) Width() float32                   { return 0.900000 }
func (Pig) Height() float32                  { return 0.900000 }
func (Piglin) ID() string                    { return "minecraft:piglin" }
func (Piglin) Width() float32                { return 0.600000 }
func (Piglin) Height() float32               { return 1.950000 }
func (PiglinBrute) ID() string               { return "minecraft:piglin_brute" }
func (PiglinBrute) Width() float32           { return 0.600000 }
func (PiglinBrute) Height() float32          { return 1.950000 }
func (Pillager) ID() string                  { return "minecraft:pillager" }
func (Pillager) Width() float32              { return 0.600000 }
func (Pillager) Height() float32             { return 1.950000 }
func (PolarBear) ID() string                 { return "minecraft:polar_bear" }
func (PolarBear) Width() float32             { return 1.400000 }
func (PolarBear) Height() float32            { return 1.400000 }
func (SplashPotion) ID() string              { return "minecraft:splash_potion" }
func (SplashPotion) Width() float32          { return 0.250000 }
func (SplashPotion) Height() float32         { return 0.250000 }
func (LingeringPotion) ID() string           { return "minecraft:lingering_potion" }
func (LingeringPotion) Width() float32       { return 0.250000 }
func (LingeringPotion) Height() float32      { return 0.250000 }
func (Pufferfish) ID() string                { return "minecraft:pufferfish" }
func (Pufferfish) Width() float32            { return 0.700000 }
func (Pufferfish) Height() float32           { return 0.700000 }
func (Rabbit) ID() string                    { return "minecraft:rabbit" }
func (Rabbit) Width() float32                { return 0.400000 }
func (Rabbit) Height() float32               { return 0.500000 }
func (Ravager) ID() string                   { return "minecraft:ravager" }
func (Ravager) Width() float32               { return 1.950000 }
func (Ravager) Height() float32              { return 2.200000 }
func (Salmon) ID() string                    { return "minecraft:salmon" }
func (Salmon) Width() float32                { return 0.700000 }
func (Salmon) Height() float32               { return 0.400000 }
func (Sheep) ID() string                     { return "minecraft:sheep" }
func (Sheep) Width() float32                 { return 0.900000 }
func (Sheep) Height() float32                { return 1.300000 }
func (Shulker) ID() string                   { return "minecraft:shulker" }
func (Shulker) Width() float32               { return 1.000000 }
func (Shulker) Height() float32              { return 1.000000 }
func (ShulkerBullet) ID() string             { return "minecraft:shulker_bullet" }
func (ShulkerBullet) Width() float32         { return 0.312500 }
func (ShulkerBullet) Height() float32        { return 0.312500 }
func (Silverfish) ID() string                { return "minecraft:silverfish" }
func (Silverfish) Width() float32            { return 0.400000 }
func (Silverfish) Height() float32           { return 0.300000 }
func (Skeleton) ID() string                  { return "minecraft:skeleton" }
func (Skeleton) Width() float32              { return 0.600000 }
func (Skeleton) Height() float32             { return 1.990000 }
func (SkeletonHorse) ID() string             { return "minecraft:skeleton_horse" }
func (SkeletonHorse) Width() float32         { return 1.396484 }
func (SkeletonHorse) Height() float32        { return 1.600000 }
func (Slime) ID() string                     { return "minecraft:slime" }
func (Slime) Width() float32                 { return 0.520000 }
func (Slime) Height() float32                { return 0.520000 }
func (SmallFireball) ID() string             { return "minecraft:small_fireball" }
func (SmallFireball) Width() float32         { return 0.312500 }
func (SmallFireball) Height() float32        { return 0.312500 }
func (Sniffer) ID() string                   { return "minecraft:sniffer" }
func (Sniffer) Width() float32               { return 1.900000 }
func (Sniffer) Height() float32              { return 1.750000 }
func (Snowball) ID() string                  { return "minecraft:snowball" }
func (Snowball) Width() float32              { return 0.250000 }
func (Snowball) Height() float32             { return 0.250000 }
func (SnowGolem) ID() string                 { return "minecraft:snow_golem" }
func (SnowGolem) Width() float32             { return 0.700000 }
func (SnowGolem) Height() float32            { return 1.900000 }
func (SpawnerMinecart) ID() string           { return "minecraft:spawner_minecart" }
func (SpawnerMinecart) Width() float32       { return 0.980000 }
func (SpawnerMinecart) Height() float32      { return 0.700000 }
func (SpectralArrow) ID() string             { return "minecraft:spectral_arrow" }
func (SpectralArrow) Width() float32         { return 0.500000 }
func (SpectralArrow) Height() float32        { return 0.500000 }
func (Spider) ID() string                    { return "minecraft:spider" }
func (Spider) Width() float32                { return 1.400000 }
func (Spider) Height() float32               { return 0.900000 }
func (SpruceBoat) ID() string                { return "minecraft:spruce_boat" }
func (SpruceBoat) Width() float32            { return 1.375000 }
func (SpruceBoat) Height() float32           { return 0.562500 }
func (SpruceChestBoat) ID() string           { return "minecraft:spruce_chest_boat" }
func (SpruceChestBoat) Width() float32       { return 1.375000 }
func (SpruceChestBoat) Height() float32      { return 0.562500 }
func (Squid) ID() string                     { return "minecraft:squid" }
func (Squid) Width() float32                 { return 0.800000 }
func (Squid) Height() float32                { return 0.800000 }
func (Stray) ID() string                     { return "minecraft:stray" }
func (Stray) Width() float32                 { return 0.600000 }
func (Stray) Height() float32                { return 1.990000 }
func (Strider) ID() string                   { return "minecraft:strider" }
func (Strider) Width() float32               { return 0.900000 }
func (Strider) Height() float32              { return 1.700000 }
func (Tadpole) ID() string                   { return "minecraft:tadpole" }
func (Tadpole) Width() float32               { return 0.400000 }
func (Tadpole) Height() float32              { return 0.300000 }
func (TextDisplay) ID() string               { return "minecraft:text_display" }
func (TextDisplay) Width() float32           { return 0.000000 }
func (TextDisplay) Height() float32          { return 0.000000 }
func (Tnt) ID() string                       { return "minecraft:tnt" }
func (Tnt) Width() float32                   { return 0.980000 }
func (Tnt) Height() float32                  { return 0.980000 }
func (TntMinecart) ID() string               { return "minecraft:tnt_minecart" }
func (TntMinecart) Width() float32           { return 0.980000 }
func (TntMinecart) Height() float32          { return 0.700000 }
func (TraderLlama) ID() string               { return "minecraft:trader_llama" }
func (TraderLlama) Width() float32           { return 0.900000 }
func (TraderLlama) Height() float32          { return 1.870000 }
func (Trident) ID() string                   { return "minecraft:trident" }
func (Trident) Width() float32               { return 0.500000 }
func (Trident) Height() float32              { return 0.500000 }
func (TropicalFish) ID() string              { return "minecraft:tropical_fish" }
func (TropicalFish) Width() float32          { return 0.500000 }
func (TropicalFish) Height() float32         { return 0.400000 }
func (Turtle) ID() string                    { return "minecraft:turtle" }
func (Turtle) Width() float32                { return 1.200000 }
func (Turtle) Height() float32               { return 0.400000 }
func (Vex) ID() string                       { return "minecraft:vex" }
func (Vex) Width() float32                   { return 0.400000 }
func (Vex) Height() float32                  { return 0.800000 }
func (Villager) ID() string                  { return "minecraft:villager" }
func (Villager) Width() float32              { return 0.600000 }
func (Villager) Height() float32             { return 1.950000 }
func (Vindicator) ID() string                { return "minecraft:vindicator" }
func (Vindicator) Width() float32            { return 0.600000 }
func (Vindicator) Height() float32           { return 1.950000 }
func (WanderingTrader) ID() string           { return "minecraft:wandering_trader" }
func (WanderingTrader) Width() float32       { return 0.600000 }
func (WanderingTrader) Height() float32      { return 1.950000 }
func (Warden) ID() string                    { return "minecraft:warden" }
func (Warden) Width() float32                { return 0.900000 }
func (Warden) Height() float32               { return 2.900000 }
func (WindCharge) ID() string                { return "minecraft:wind_charge" }
func (WindCharge) Width() float32            { return 0.312500 }
func (WindCharge) Height() float32           { return 0.312500 }
func (Witch) ID() string                     { return "minecraft:witch" }
func (Witch) Width() float32                 { return 0.600000 }
func (Witch) Height() float32                { return 1.950000 }
func (Wither) ID() string                    { return "minecraft:wither" }
func (Wither) Width() float32                { return 0.900000 }
func (Wither) Height() float32               { return 3.500000 }
func (WitherSkeleton) ID() string            { return "minecraft:wither_skeleton" }
func (WitherSkeleton) Width() float32        { return 0.700000 }
func (WitherSkeleton) Height() float32       { return 2.400000 }
func (WitherSkull) ID() string               { return "minecraft:wither_skull" }
func (WitherSkull) Width() float32           { return 0.312500 }
func (WitherSkull) Height() float32          { return 0.312500 }
func (Wolf) ID() string                      { return "minecraft:wolf" }
func (Wolf) Width() float32                  { return 0.600000 }
func (Wolf) Height() float32                 { return 0.850000 }
func (Zoglin) ID() string                    { return "minecraft:zoglin" }
func (Zoglin) Width() float32                { return 1.396484 }
func (Zoglin) Height() float32               { return 1.400000 }
func (Zombie) ID() string                    { return "minecraft:zombie" }
func (Zombie) Width() float32                { return 0.600000 }
func (Zombie) Height() float32               { return 1.950000 }
func (ZombieHorse) ID() string               { return "minecraft:zombie_horse" }
func (ZombieHorse) Width() float32           { return 1.396484 }
func (ZombieHorse) Height() float32          { return 1.600000 }
func (ZombieNautilus) ID() string            { return "minecraft:zombie_nautilus" }
func (ZombieNautilus) Width() float32        { return 0.875000 }
func (ZombieNautilus) Height() float32       { return 0.950000 }
func (ZombieVillager) ID() string            { return "minecraft:zombie_villager" }
func (ZombieVillager) Width() float32        { return 0.600000 }
func (ZombieVillager) Height() float32       { return 1.950000 }
func (ZombifiedPiglin) ID() string           { return "minecraft:zombified_piglin" }
func (ZombifiedPiglin) Width() float32       { return 0.600000 }
func (ZombifiedPiglin) Height() float32      { return 1.950000 }
func (Player) ID() string                    { return "minecraft:player" }
func (Player) Width() float32                { return 0.600000 }
func (Player) Height() float32               { return 1.800000 }
func (FishingBobber) ID() string             { return "minecraft:fishing_bobber" }
func (FishingBobber) Width() float32         { return 0.250000 }
func (FishingBobber) Height() float32        { return 0.250000 }

var FromID = map[string]Entity{
	"minecraft:acacia_boat":            AcaciaBoat{},
	"minecraft:acacia_chest_boat":      AcaciaChestBoat{},
	"minecraft:allay":                  Allay{},
	"minecraft:area_effect_cloud":      AreaEffectCloud{},
	"minecraft:armadillo":              Armadillo{},
	"minecraft:armor_stand":            ArmorStand{},
	"minecraft:arrow":                  Arrow{},
	"minecraft:axolotl":                Axolotl{},
	"minecraft:bamboo_chest_raft":      BambooChestRaft{},
	"minecraft:bamboo_raft":            BambooRaft{},
	"minecraft:bat":                    Bat{},
	"minecraft:bee":                    Bee{},
	"minecraft:birch_boat":             BirchBoat{},
	"minecraft:birch_chest_boat":       BirchChestBoat{},
	"minecraft:blaze":                  Blaze{},
	"minecraft:block_display":          BlockDisplay{},
	"minecraft:bogged":                 Bogged{},
	"minecraft:breeze":                 Breeze{},
	"minecraft:breeze_wind_charge":     BreezeWindCharge{},
	"minecraft:camel":                  Camel{},
	"minecraft:camel_husk":             CamelHusk{},
	"minecraft:cat":                    Cat{},
	"minecraft:cave_spider":            CaveSpider{},
	"minecraft:cherry_boat":            CherryBoat{},
	"minecraft:cherry_chest_boat":      CherryChestBoat{},
	"minecraft:chest_minecart":         ChestMinecart{},
	"minecraft:chicken":                Chicken{},
	"minecraft:cod":                    Cod{},
	"minecraft:copper_golem":           CopperGolem{},
	"minecraft:command_block_minecart": CommandBlockMinecart{},
	"minecraft:cow":                    Cow{},
	"minecraft:creaking":               Creaking{},
	"minecraft:creeper":                Creeper{},
	"minecraft:dark_oak_boat":          DarkOakBoat{},
	"minecraft:dark_oak_chest_boat":    DarkOakChestBoat{},
	"minecraft:dolphin":                Dolphin{},
	"minecraft:donkey":                 Donkey{},
	"minecraft:dragon_fireball":        DragonFireball{},
	"minecraft:drowned":                Drowned{},
	"minecraft:egg":                    Egg{},
	"minecraft:elder_guardian":         ElderGuardian{},
	"minecraft:enderman":               Enderman{},
	"minecraft:endermite":              Endermite{},
	"minecraft:ender_dragon":           EnderDragon{},
	"minecraft:ender_pearl":            EnderPearl{},
	"minecraft:end_crystal":            EndCrystal{},
	"minecraft:evoker":                 Evoker{},
	"minecraft:evoker_fangs":           EvokerFangs{},
	"minecraft:experience_bottle":      ExperienceBottle{},
	"minecraft:experience_orb":         ExperienceOrb{},
	"minecraft:eye_of_ender":           EyeOfEnder{},
	"minecraft:falling_block":          FallingBlock{},
	"minecraft:fireball":               Fireball{},
	"minecraft:firework_rocket":        FireworkRocket{},
	"minecraft:fox":                    Fox{},
	"minecraft:frog":                   Frog{},
	"minecraft:furnace_minecart":       FurnaceMinecart{},
	"minecraft:ghast":                  Ghast{},
	"minecraft:happy_ghast":            HappyGhast{},
	"minecraft:giant":                  Giant{},
	"minecraft:glow_item_frame":        GlowItemFrame{},
	"minecraft:glow_squid":             GlowSquid{},
	"minecraft:goat":                   Goat{},
	"minecraft:guardian":               Guardian{},
	"minecraft:hoglin":                 Hoglin{},
	"minecraft:hopper_minecart":        HopperMinecart{},
	"minecraft:horse":                  Horse{},
	"minecraft:husk":                   Husk{},
	"minecraft:illusioner":             Illusioner{},
	"minecraft:interaction":            Interaction{},
	"minecraft:iron_golem":             IronGolem{},
	"minecraft:item":                   Item{},
	"minecraft:item_display":           ItemDisplay{},
	"minecraft:item_frame":             ItemFrame{},
	"minecraft:jungle_boat":            JungleBoat{},
	"minecraft:jungle_chest_boat":      JungleChestBoat{},
	"minecraft:leash_knot":             LeashKnot{},
	"minecraft:lightning_bolt":         LightningBolt{},
	"minecraft:llama":                  Llama{},
	"minecraft:llama_spit":             LlamaSpit{},
	"minecraft:magma_cube":             MagmaCube{},
	"minecraft:mangrove_boat":          MangroveBoat{},
	"minecraft:mangrove_chest_boat":    MangroveChestBoat{},
	"minecraft:mannequin":              Mannequin{},
	"minecraft:marker":                 Marker{},
	"minecraft:minecart":               Minecart{},
	"minecraft:mooshroom":              Mooshroom{},
	"minecraft:mule":                   Mule{},
	"minecraft:nautilus":               Nautilus{},
	"minecraft:oak_boat":               OakBoat{},
	"minecraft:oak_chest_boat":         OakChestBoat{},
	"minecraft:ocelot":                 Ocelot{},
	"minecraft:ominous_item_spawner":   OminousItemSpawner{},
	"minecraft:painting":               Painting{},
	"minecraft:pale_oak_boat":          PaleOakBoat{},
	"minecraft:pale_oak_chest_boat":    PaleOakChestBoat{},
	"minecraft:panda":                  Panda{},
	"minecraft:parched":                Parched{},
	"minecraft:parrot":                 Parrot{},
	"minecraft:phantom":                Phantom{},
	"minecraft:pig":                    Pig{},
	"minecraft:piglin":                 Piglin{},
	"minecraft:piglin_brute":           PiglinBrute{},
	"minecraft:pillager":               Pillager{},
	"minecraft:polar_bear":             PolarBear{},
	"minecraft:splash_potion":          SplashPotion{},
	"minecraft:lingering_potion":       LingeringPotion{},
	"minecraft:pufferfish":             Pufferfish{},
	"minecraft:rabbit":                 Rabbit{},
	"minecraft:ravager":                Ravager{},
	"minecraft:salmon":                 Salmon{},
	"minecraft:sheep":                  Sheep{},
	"minecraft:shulker":                Shulker{},
	"minecraft:shulker_bullet":         ShulkerBullet{},
	"minecraft:silverfish":             Silverfish{},
	"minecraft:skeleton":               Skeleton{},
	"minecraft:skeleton_horse":         SkeletonHorse{},
	"minecraft:slime":                  Slime{},
	"minecraft:small_fireball":         SmallFireball{},
	"minecraft:sniffer":                Sniffer{},
	"minecraft:snowball":               Snowball{},
	"minecraft:snow_golem":             SnowGolem{},
	"minecraft:spawner_minecart":       SpawnerMinecart{},
	"minecraft:spectral_arrow":         SpectralArrow{},
	"minecraft:spider":                 Spider{},
	"minecraft:spruce_boat":            SpruceBoat{},
	"minecraft:spruce_chest_boat":      SpruceChestBoat{},
	"minecraft:squid":                  Squid{},
	"minecraft:stray":                  Stray{},
	"minecraft:strider":                Strider{},
	"minecraft:tadpole":                Tadpole{},
	"minecraft:text_display":           TextDisplay{},
	"minecraft:tnt":                    Tnt{},
	"minecraft:tnt_minecart":           TntMinecart{},
	"minecraft:trader_llama":           TraderLlama{},
	"minecraft:trident":                Trident{},
	"minecraft:tropical_fish":          TropicalFish{},
	"minecraft:turtle":                 Turtle{},
	"minecraft:vex":                    Vex{},
	"minecraft:villager":               Villager{},
	"minecraft:vindicator":             Vindicator{},
	"minecraft:wandering_trader":       WanderingTrader{},
	"minecraft:warden":                 Warden{},
	"minecraft:wind_charge":            WindCharge{},
	"minecraft:witch":                  Witch{},
	"minecraft:wither":                 Wither{},
	"minecraft:wither_skeleton":        WitherSkeleton{},
	"minecraft:wither_skull":           WitherSkull{},
	"minecraft:wolf":                   Wolf{},
	"minecraft:zoglin":                 Zoglin{},
	"minecraft:zombie":                 Zombie{},
	"minecraft:zombie_horse":           ZombieHorse{},
	"minecraft:zombie_nautilus":        ZombieNautilus{},
	"minecraft:zombie_villager":        ZombieVillager{},
	"minecraft:zombified_piglin":       ZombifiedPiglin{},
	"minecraft:player":                 Player{},
	"minecraft:fishing_bobber":         FishingBobber{},
}

var ToID = map[ID]Entity{
	0:   AcaciaBoat{},
	1:   AcaciaChestBoat{},
	2:   Allay{},
	3:   AreaEffectCloud{},
	4:   Armadillo{},
	5:   ArmorStand{},
	6:   Arrow{},
	7:   Axolotl{},
	8:   BambooChestRaft{},
	9:   BambooRaft{},
	10:  Bat{},
	11:  Bee{},
	12:  BirchBoat{},
	13:  BirchChestBoat{},
	14:  Blaze{},
	15:  BlockDisplay{},
	16:  Bogged{},
	17:  Breeze{},
	18:  BreezeWindCharge{},
	19:  Camel{},
	20:  CamelHusk{},
	21:  Cat{},
	22:  CaveSpider{},
	23:  CherryBoat{},
	24:  CherryChestBoat{},
	25:  ChestMinecart{},
	26:  Chicken{},
	27:  Cod{},
	28:  CopperGolem{},
	29:  CommandBlockMinecart{},
	30:  Cow{},
	31:  Creaking{},
	32:  Creeper{},
	33:  DarkOakBoat{},
	34:  DarkOakChestBoat{},
	35:  Dolphin{},
	36:  Donkey{},
	37:  DragonFireball{},
	38:  Drowned{},
	39:  Egg{},
	40:  ElderGuardian{},
	41:  Enderman{},
	42:  Endermite{},
	43:  EnderDragon{},
	44:  EnderPearl{},
	45:  EndCrystal{},
	46:  Evoker{},
	47:  EvokerFangs{},
	48:  ExperienceBottle{},
	49:  ExperienceOrb{},
	50:  EyeOfEnder{},
	51:  FallingBlock{},
	52:  Fireball{},
	53:  FireworkRocket{},
	54:  Fox{},
	55:  Frog{},
	56:  FurnaceMinecart{},
	57:  Ghast{},
	58:  HappyGhast{},
	59:  Giant{},
	60:  GlowItemFrame{},
	61:  GlowSquid{},
	62:  Goat{},
	63:  Guardian{},
	64:  Hoglin{},
	65:  HopperMinecart{},
	66:  Horse{},
	67:  Husk{},
	68:  Illusioner{},
	69:  Interaction{},
	70:  IronGolem{},
	71:  Item{},
	72:  ItemDisplay{},
	73:  ItemFrame{},
	74:  JungleBoat{},
	75:  JungleChestBoat{},
	76:  LeashKnot{},
	77:  LightningBolt{},
	78:  Llama{},
	79:  LlamaSpit{},
	80:  MagmaCube{},
	81:  MangroveBoat{},
	82:  MangroveChestBoat{},
	83:  Mannequin{},
	84:  Marker{},
	85:  Minecart{},
	86:  Mooshroom{},
	87:  Mule{},
	88:  Nautilus{},
	89:  OakBoat{},
	90:  OakChestBoat{},
	91:  Ocelot{},
	92:  OminousItemSpawner{},
	93:  Painting{},
	94:  PaleOakBoat{},
	95:  PaleOakChestBoat{},
	96:  Panda{},
	97:  Parched{},
	98:  Parrot{},
	99:  Phantom{},
	100: Pig{},
	101: Piglin{},
	102: PiglinBrute{},
	103: Pillager{},
	104: PolarBear{},
	105: SplashPotion{},
	106: LingeringPotion{},
	107: Pufferfish{},
	108: Rabbit{},
	109: Ravager{},
	110: Salmon{},
	111: Sheep{},
	112: Shulker{},
	113: ShulkerBullet{},
	114: Silverfish{},
	115: Skeleton{},
	116: SkeletonHorse{},
	117: Slime{},
	118: SmallFireball{},
	119: Sniffer{},
	120: Snowball{},
	121: SnowGolem{},
	122: SpawnerMinecart{},
	123: SpectralArrow{},
	124: Spider{},
	125: SpruceBoat{},
	126: SpruceChestBoat{},
	127: Squid{},
	128: Stray{},
	129: Strider{},
	130: Tadpole{},
	131: TextDisplay{},
	132: Tnt{},
	133: TntMinecart{},
	134: TraderLlama{},
	135: Trident{},
	136: TropicalFish{},
	137: Turtle{},
	138: Vex{},
	139: Villager{},
	140: Vindicator{},
	141: WanderingTrader{},
	142: Warden{},
	143: WindCharge{},
	144: Witch{},
	145: Wither{},
	146: WitherSkeleton{},
	147: WitherSkull{},
	148: Wolf{},
	149: Zoglin{},
	150: Zombie{},
	151: ZombieHorse{},
	152: ZombieNautilus{},
	153: ZombieVillager{},
	154: ZombifiedPiglin{},
	155: Player{},
	156: FishingBobber{},
}
